### PR TITLE
CFMODULE can only import CF template files CF11

### PR DESCRIPTION
**Pull request by jphustman**
ColdFusion 11 CFMODULE will not import .html files.

### CODE REVIEW

**Comment by timmixell** [comment]
i'm just trying colddoc for the first time, and happened across this branch. it fixed my CF11 woes. cheers!

**Comment by NathanStrutz** [comment]
@markmandel Please merge!

**Comment by markmandel** [comment]
You should really go check out https://github.com/Ortus-Solutions/DocBox - it's actually supported and stuff ;)

Let me know if it doesn't work for you.

**Comment by markmandel** [comment]
Closing.

**Pull request closed without merging**
